include: '/.gitlab/job-templates.yml'

variables:
  TEXTQL_RELEASE: '2.0.3.20221220'
  TEXTQL_REVISION: fca00ecc76c8
  TEXTQL_VERSION: '2.0.3'

compile.textql:
  stage: build
  image: golang:1.14
  script:
    - GO111MODULE=on go get -ldflags "-X main.VERSION=${TEXTQL_VERSION}-${TEXTQL_REVISION} -s"  github.com/dinedal/textql/...@${TEXTQL_REVISION}
    - mkdir -p textql
    - mv /go/bin/textql ./textql/
    - cp -vr /go/pkg/mod/github.com/dinedal/textql\@*/LICENSE ./textql/
    - cp -vr /go/pkg/mod/github.com/dinedal/textql\@*/Readme.md ./textql/
    - cp -vr /go/pkg/mod/github.com/dinedal/textql\@*/man/textql.1 ./textql/
  only:
    changes:
      - "textql/*"
  artifacts:
    paths:
      - textql/

rpm.textql:
  extends: .rpm-template
  variables:
    PACKAGE_NAME: 'textql'
    VERSION: $TEXTQL_RELEASE
  dependencies:
    - compile.textql
  only:
    changes:
      - "textql/*"
  script:
    - cat ~/.rpmmacros
    - >
      fpm -s dir -t rpm -n ${PACKAGE_NAME} -v ${VERSION}
      --description 'Allows you to easily execute SQL against structured text like CSV or TSV.'
      --rpm-summary 'Allows you to easily execute SQL against structured text like CSV or TSV.'
      --vendor morawskim
      --license 'MIT'
      --url https://github.com/dinedal/textql
      ./textql/textql=/usr/bin/
      ./textql/Readme.md=/usr/share/doc/packages/${PACKAGE_NAME}/README.md
      ./textql/LICENSE=/usr/share/licenses/${PACKAGE_NAME}/LICENSE
      ./textql/textql.1=/usr/share/man/man1/textql.1
  artifacts:
    paths:
      - ${PACKAGE_NAME}-${VERSION}-1.x86_64.rpm
