variables:
  NETSED_VERSION: '1.2'

compile.netsed:
  stage: build
  image: gcc:8.4.0
  script:
    - apt-get -y update
    - apt-get -y install doxygen graphviz
    - wget -Onetsed.tar.gz http://silicone.homelinux.org/release/netsed/netsed-${NETSED_VERSION}.tar.gz
    - tar xvzf netsed.tar.gz
    - cd netsed-${NETSED_VERSION}
    - make
    - make doc
    - cp -v NEWS README ./html
  only:
    changes:
      - "netsed/*"
  artifacts:
    paths:
      - netsed-${NETSED_VERSION}/html
      - netsed-${NETSED_VERSION}/LICENSE
      - netsed-${NETSED_VERSION}/netsed

rpm.netsed:
    stage: package
    image: alanfranz/fpm-within-docker:centos-7
    variables:
      PACKAGE_NAME: 'netsed'
      VERSION: $NETSED_VERSION
    dependencies:
      - compile.netsed
    only:
      changes:
        - "netsed/*"
    script:
      - |
        cat > ~/.rpmmacros << EOF
        %packager Marcin Morawski <marcin@morawskim.pl>
        %vendor morawskim
        EOF
      - cat ~/.rpmmacros
      - >
        fpm -s dir -t rpm -n ${PACKAGE_NAME} -v ${VERSION}
        --description "NetSED is small and handful utility designed to alter the contents of packets forwarded through your network in real time. It is really useful for network hackers in following applications: * black-box protocol auditing - whenever there are two or more proprietary boxes communicating over undocumented protocol (by enforcing   changes in ongoing transmissions, you will be able to test if tested application is secure), * fuzz-alike experiments, integrity tests - whenever you want to test stability of the application and see how it ensures data integrity, * other common applications - fooling other people, content filtering, etc - choose whatever you want to."
        --rpm-summary "A tool to modify network packets"
        --vendor morawskim
        --license 'GPLv2+'
        --url http://silicone.homelinux.org/projects/netsed/
        ./netsed-${NETSED_VERSION}/netsed=/usr/bin/
        ./netsed-${NETSED_VERSION}/html=/usr/share/doc/packages/${PACKAGE_NAME}
        ./netsed-${NETSED_VERSION}/LICENSE=/usr/share/licenses/${PACKAGE_NAME}/LICENSE
    artifacts:
      paths:
        - ${PACKAGE_NAME}-${VERSION}-1.x86_64.rpm
