include: '/.gitlab/job-templates.yml'

stages:
  - build
  - package

variables:
  PACKAGE_NAME: 'yq'
  VERSION: '4.32.2'

compile:
  stage: build
  image: golang:1.20
  script:
    - wget -Oyq.tar.gz https://github.com/mikefarah/yq/archive/v${VERSION}.tar.gz
    - tar xvzf yq.tar.gz
    - cd yq-${VERSION}
    - go build
  only:
    changes:
      - "yq/*"
  artifacts:
    paths:
      - yq-${VERSION}/yq
      - yq-${VERSION}/README.md
      - yq-${VERSION}/LICENSE

rpm:
  extends: .rpm-template
  dependencies:
    - compile
  only:
    changes:
      - "yq/*"
  script:
    - >
      fpm -s dir -t rpm -n ${PACKAGE_NAME} -v ${VERSION}
      --description 'a lightweight and portable command-line YAML, JSON and XML processor. yq uses jq like syntax but works with yaml files as well as json, xml, properties, csv and tsv. It doesn't yet support everything jq does - but it does support the most common operations and functions, and more is being added continuously.'
      --rpm-summary 'yq is a portable command-line YAML, JSON, XML, CSV, TOML and properties processor'
      --vendor morawskim
      --license MIT
      --url https://github.com/mikefarah/yq
      yq-${VERSION}/yq=/usr/bin/
      yq-${VERSION}/README.md=/usr/share/doc/packages/${PACKAGE_NAME}/
      yq-${VERSION}/LICENSE=/usr/share/licenses/${PACKAGE_NAME}/
  artifacts:
    paths:
      - ${PACKAGE_NAME}-${VERSION}-1.x86_64.rpm
