include: '/.gitlab/job-templates.yml'

stages:
  - build
  - package

variables:
  PACKAGE_NAME: 'php-docs'

compile:
  stage: build
  image: php:7.4-cli
  script:
    - apt-get -y update && apt-get install -y git
    - git clone https://github.com/php/doc-en.git en
    - git clone https://github.com/php/doc-base.git
    - git clone https://github.com/php/phd.git
    - php doc-base/configure.php
    # Build man pages
    - php -dmemory_limit=512M phd/render.php --docbook doc-base/.manual.xml --package PHP --format manpage --output docs/man
    # Build xhtml
    - php -dmemory_limit=512M phd/render.php --docbook doc-base/.manual.xml --package PHP --format xhtml --outputfilename html --output docs/xhtml
  only:
    changes:
      - "php-docs/*"
  artifacts:
    paths:
      - docs/
      - doc-base/README.md
      - doc-base/LICENSE

rpm:
  extends: .rpm-template
  dependencies:
    - compile
  only:
    changes:
      - "php-docs/*"
  script:
    - VERSION=$(date +\%Y\%m\%d)
    - >
      fpm -s dir -t rpm -n ${PACKAGE_NAME} -v ${VERSION}
      --description 'The PHP Manual in xhtml and man pages formats'
      --rpm-summary 'The PHP Manual in xhtml and man pages formats'
      --vendor morawskim
      --license MIT
      --url http://doc.php.net
      -a all
      doc-base/README.md=/usr/share/doc/packages/${PACKAGE_NAME}/
      doc-base/LICENSE=/usr/share/licenses/${PACKAGE_NAME}/
      docs/man/php-functions/=/opt/php/docs/man/man3
      docs/xhtml/php-chunked-xhtml/=/opt/php/docs/xhtml
  artifacts:
    paths:
      - ${PACKAGE_NAME}-*.noarch.rpm
