include: '/.gitlab/job-templates.yml'

variables:
  TMPMAIL_VERSION: '1.2.3'

compile.tmpmail:
  stage: build
  image: rust:1.44
  script:
    - wget -Otmpmail.tar.gz https://github.com/sdushantha/tmpmail/archive/refs/tags/v${TMPMAIL_VERSION}.tar.gz
    - tar xzvf tmpmail.tar.gz
    - cd tmpmail-${TMPMAIL_VERSION}
    - chmod a+x tmpmail
  only:
    changes:
      - "tmpmail/*"
  artifacts:
    paths:
      - tmpmail-${TMPMAIL_VERSION}/LICENSE
      - tmpmail-${TMPMAIL_VERSION}/README.md
      - tmpmail-${TMPMAIL_VERSION}/tmpmail

rpm.tmpmail:
  extends: .rpm-template
  variables:
    PACKAGE_NAME: 'tmpmail'
  dependencies:
    - compile.tmpmail
  only:
    changes:
      - "tmpmail/*"
  script:
    - >
      fpm -s dir -t rpm -n ${PACKAGE_NAME} -v ${TMPMAIL_VERSION}
      --description 'tmpmail is a command line utility that allows you to create a temporary email address and receive emails to the temporary email address. It uses 1secmail API to receive the emails.'
      --rpm-summary 'A temporary email right from your terminal'
      --vendor morawskim
      --license 'MIT'
      --url https://github.com/sdushantha/tmpmail
      -a all
      --depends w3m
      --depends curl
      --depends jq
      --depends awk
      ./tmpmail-${TMPMAIL_VERSION}/tmpmail=/usr/bin/
      ./tmpmail-${TMPMAIL_VERSION}/LICENSE=/usr/share/licenses/${PACKAGE_NAME}/LICENSE
      ./tmpmail-${TMPMAIL_VERSION}/README.md=/usr/share/doc/packages/${PACKAGE_NAME}/README.md
  artifacts:
    paths:
      - ${PACKAGE_NAME}-*.rpm
