variables:
  LICENSE_VERSION: 5.0.4

compile.license:
  stage: build
  image: golang:1.19
  script:
    - go install github.com/nishanths/license/v5@v${LICENSE_VERSION}
    - mkdir -p bin
    - mv /go/bin/license ./bin/
  only:
    changes:
      - "license/*"
  artifacts:
    paths:
      - ./bin/license

rpm.license:
    stage: package
    image: alanfranz/fpm-within-docker:centos-7
    variables:
      PACKAGE_NAME: 'license'
      VERSION: $LICENSE_VERSION
    dependencies:
      - compile.license
    only:
      changes:
        - "license/*"
    before_script:
      - gpg --import $GPG_PRIVATE_KEY_TO_SIGN
      - echo -e "5\ny\n" | gpg --no-tty --command-fd 0 --edit-key "morawskim" trust
    script:
      - |
        cat > ~/.rpmmacros << EOF
        %packager Marcin Morawski <marcin@morawskim.pl>
        %_signature gpg
        %_gpg_name morawskim Signing Key
        %vendor morawskim
        EOF
      - cat ~/.rpmmacros
      - >
        fpm -s dir -t rpm -n ${PACKAGE_NAME} -v ${VERSION}
        --description 'license is a command line tool to create LICENSE files.'
        --rpm-summary 'Generate license files'
        --vendor morawskim
        --license MIT
        --url https://github.com/nishanths/license
        ./bin/license=/usr/bin/
      - rpm --addsign *.rpm
    artifacts:
      paths:
        - ${PACKAGE_NAME}-${VERSION}-1.x86_64.rpm
