include: '/.gitlab/job-templates.yml'

stages:
  - package

variables:
  PACKAGE_NAME: 'fake-libXtst'
  VERSION: '0.1.0'
  SPECFILE: 'libXtst/fake-libXtst.spec'

rpm:
  extends: .rpm-template
  image:
    name: morawskim/opensuse-leap-debug:15.0.2020-11-13
    entrypoint: [ "/bin/bash", "-c" ]
  script:
    - cat ~/.rpmmacros
    - zypper --non-interactive in rpmdevtools rpm-build
    - mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
    - rpmdev-spectool --all --get-files --directory rpmbuild/SOURCES/ ${SPECFILE}
    - rpmbuild -ba --define="_sourcedir $PWD" --define="_topdir $PWD/rpmbuild" ${SPECFILE}
    - mv rpmbuild/RPMS/noarch/fake-libXtst-*.noarch.rpm .
  only:
    changes:
      - "libXtst/*"
  artifacts:
    paths:
      - fake-libXtst-*.noarch.rpm
