stages:
  - build
  - package

variables:
  PACKAGE_NAME: 'ventoy'
  VERSION: '1.0.38'

compile:
  stage: build
  image: golang:1.14
  script:
    - wget -Oventoy.tar.gz https://github.com/ventoy/Ventoy/releases/download/v${VERSION}/ventoy-${VERSION}-linux.tar.gz
    - tar xvzf ventoy.tar.gz
    - cd ventoy-${VERSION}
  only:
    changes:
      - "ventoy/*"
  artifacts:
    paths:
      - ventoy-${VERSION}/

rpm:
    stage: package
    image: alanfranz/fpm-within-docker:centos-7
    dependencies:
      - compile
    only:
      changes:
        - "ventoy/*"
    before_script:
      - gpg --import $GPG_PRIVATE_KEY_TO_SIGN
      - echo -e "5\ny\n" | gpg --no-tty --command-fd 0 --edit-key "morawskim" trust
    script:
      - |
        cat > ~/.rpmmacros << EOF
        %packager Marcin Morawski <marcin@morawskim.pl>
        %_signature gpg
        %_gpg_name morawskim Signing Key
        %vendor morawskim
        EOF
      - >
        fpm -s dir -t rpm -n ${PACKAGE_NAME} -v ${VERSION}
        --description 'Ventoy is an open source tool to create bootable USB drive for ISO/WIM/IMG/VHD(x)/EFI files. With ventoy, you do not need to format the disk over and over, you just need to copy the image files to the USB drive and boot it. You can copy many image files at a time and ventoy will give you a boot menu to select them.'
        --rpm-summary 'A new bootable USB solution'
        --vendor morawskim
        --license GPLv3+
        --url https://github.com/ventoy/Ventoy
        ventoy-${VERSION}/=/opt/ventoy/
      - rpm --addsign *.rpm
    artifacts:
      paths:
        - ${PACKAGE_NAME}-${VERSION}-1.x86_64.rpm
