include: '/.gitlab/job-templates.yml'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - packer/*
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
      when: always

stages:
  - build
  - package

variables:
  PACKAGE_NAME: 'packer'
  VERSION: '1.6.5'

compile:
  stage: build
  image: golang:1.14
  script:
    - wget -Opacker.tar.gz https://github.com/hashicorp/packer/archive/v${VERSION}.tar.gz
    - tar xzvf packer.tar.gz
    - mkdir -p $GOPATH/src/github.com/hashicorp
    - ln -s $PWD/packer-${VERSION} $GOPATH/src/github.com/hashicorp/packer
    - pushd /go/src/github.com/hashicorp/packer
    - go build -o bin/packer .
  artifacts:
    paths:
      - packer-${VERSION}/bin/packer
      - packer-${VERSION}/LICENSE
      - packer-${VERSION}/README.md
      - packer-${VERSION}/CHANGELOG.md

rpm:
  extends: .rpm-template
  dependencies:
    - compile
  script:
    - >
      fpm -s dir -t rpm -n ${PACKAGE_NAME} -v ${VERSION}
      --description 'Packer is a free and open source tool for creating golden images for multiple platforms from a single source configuration.'
      --rpm-summary 'Packer is a tool for creating identical machine images for multiple platforms from a single source configuration'
      --vendor morawskim
      --license MPL-2.0
      --url https://www.packer.io/
      packer-${VERSION}/bin/packer=/usr/bin/
      packer-${VERSION}/CHANGELOG.md=/usr/share/doc/packages/${PACKAGE_NAME}/
      packer-${VERSION}/README.md=/usr/share/doc/packages/${PACKAGE_NAME}/
      packer-${VERSION}/LICENSE=/usr/share/licenses/${PACKAGE_NAME}/
  artifacts:
    paths:
      - ${PACKAGE_NAME}-${VERSION}-1.x86_64.rpm
