compile.delta:
  stage: build
  image: rust:1.44
  variables:
    VERSION: '0.1.1'
  script:
    - apt-get -y update
    - apt-get -y install libclang1 llvm
    - wget -Odelta.tar.gz https://github.com/dandavison/delta/archive/${VERSION}.tar.gz
    - tar xvzf delta.tar.gz
    - cd delta-${VERSION}
    - cargo build --release
  only:
    changes:
      - "delta/*"
  artifacts:
    paths:
      - delta-${VERSION}/target/release/delta
      - delta-${VERSION}/completion/bash/completion.sh
      - delta-${VERSION}/LICENSE
      - delta-${VERSION}/README.md

rpm.delta:
    stage: package
    image: alanfranz/fpm-within-docker:centos-7
    variables:
      PACKAGE_NAME: 'git-delta'
      VERSION: '0.1.1'
    dependencies:
      - compile.delta
    only:
      changes:
        - "delta/*"
    script:
      - |
        cat > ~/.rpmmacros << EOF
        %packager Marcin Morawski <marcin@morawskim.pl>
        %vendor morawskim
        EOF
      - >
        fpm -s dir -t rpm -n ${PACKAGE_NAME} -v ${VERSION}
        --description 'Delta provides language syntax-highlighting, within-line insertion/deletion detection, and restructured diff output for git on the command line.'
        --rpm-summary 'A syntax-highlighter for git and diff output'
        --vendor morawskim
        --license MIT
        --url https://github.com/dandavison/delta
        delta-${VERSION}/target/release/delta=/usr/bin/
        delta-${VERSION}/completion/bash/completion.sh=/etc/bash-completion/completions/delta.sh
        delta-${VERSION}/README.md=/usr/share/doc/packages/${PACKAGE_NAME}/
        delta-${VERSION}/LICENSE=/usr/share/licenses/${PACKAGE_NAME}/
    artifacts:
      paths:
        - ${PACKAGE_NAME}-${VERSION}-1.x86_64.rpm
