include: '/.gitlab/job-templates.yml'

variables:
  DIVE_VERSION: '0.10.0'

compile.dive:
  stage: build
  image: golang:1.14
  script:
    # see: https://github.com/wagoodman/dive/issues/361 and https://github.com/wagoodman/dive/issues/392
    - git clone https://github.com/wagoodman/dive.git dive-repository
    - pushd dive-repository
    - git checkout v${DIVE_VERSION}
    - go install .
    - make build
    - popd
    - mkdir -p dive-${DIVE_VERSION}
    - mv dive-repository/dist/dive_linux_amd64/dive dive-${DIVE_VERSION}/dive
    - cp dive-repository/LICENSE dive-repository/README.md dive-${DIVE_VERSION}
  only:
    changes:
      - "dive/*"
  artifacts:
    paths:
      - dive-${DIVE_VERSION}/

rpm.dive:
  extends: .rpm-template
  variables:
    PACKAGE_NAME: 'dive'
    VERSION: $DIVE_VERSION
  dependencies:
    - compile.dive
  only:
    changes:
      - "dive/*"
  script:
    - cat ~/.rpmmacros
    - >
      fpm -s dir -t rpm -n ${PACKAGE_NAME} -v ${VERSION}
      --description 'A tool for exploring a docker image, layer contents, and discovering ways to shrink the size of your Docker/OCI image.'
      --rpm-summary 'A tool for exploring a docker image, layer contents, and discovering ways to shrink the size of your Docker/OCI image.'
      --vendor morawskim
      --license 'MIT'
      --url https://github.com/wagoodman/dive
      ./dive-${DIVE_VERSION}/dive=/usr/bin/
      ./dive-${DIVE_VERSION}/README.md=/usr/share/doc/packages/${PACKAGE_NAME}/README.md
      ./dive-${DIVE_VERSION}/LICENSE=/usr/share/licenses/${PACKAGE_NAME}/LICENSE
  artifacts:
    paths:
      - ${PACKAGE_NAME}-*.x86_64.rpm
