stages:
  - package

variables:
  PACKAGE_NAME: 'python-pipx'
  SPECFILE: 'python-pipx/python-pipx.spec'

rpm:
  stage: package
  image:
    name: opensuse/leap:15.1
    entrypoint: ["/bin/bash", "-c"]
  script:
    - |
      cat > ~/.rpmmacros << EOF
      %packager Marcin Morawski <marcin@morawskim.pl>
      %vendor morawskim
      EOF
    - cat ~/.rpmmacros
    - zypper --non-interactive in python-rpm-macros python2-devel python3-devel python2-setuptools python3-setuptools fdupes rpmdevtools rpm-build
    - mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
    - rpmdev-spectool --all --get-files --directory rpmbuild/SOURCES/ --define 'is_spectool 1' ${SPECFILE}
    - rpmbuild -ba --define="_topdir $PWD/rpmbuild" ${SPECFILE}
    - mv rpmbuild/RPMS/noarch/python*-pipx-*.noarch.rpm .
  only:
    changes:
      - "python-pipx/*"
  artifacts:
    paths:
      - python*-pipx-*.noarch.rpm
