include: '/.gitlab/job-templates.yml'

stages:
  - package

variables:
  PACKAGE_NAME: 'python-pipx'
  SPECFILE: 'python-pipx/python-pipx.spec'

rpm:
  extends: .rpm-template
  image:
    name: opensuse/tumbleweed
    entrypoint: [ "/bin/bash", "-c" ]
  script:
    - cat ~/.rpmmacros
    - zypper --non-interactive in python-rpm-macros python2-setuptools fdupes rpmdevtools rpm-build python38-devel python38-setuptools python39-devel python39-setuptools python310-devel python310-setuptools
    - mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
    - rpmdev-spectool --all --get-files --directory rpmbuild/SOURCES/ --define 'is_spectool 1' ${SPECFILE}
    - rpmbuild -ba --define="_topdir $PWD/rpmbuild" ${SPECFILE}
    - mv rpmbuild/RPMS/noarch/python*-pipx-*.noarch.rpm .
  only:
    changes:
      - "python-pipx/*"
  artifacts:
    paths:
      - python*-pipx-*.noarch.rpm
