include: '/.gitlab/job-templates.yml'

stages:
  - build
  - package

variables:
  PACKAGE_NAME: 'duf'
  VERSION: '0.8.1'

compile.duf:
  stage: build
  image: golang:1.19
  script:
    - go install github.com/muesli/duf@v$VERSION
    - mkdir -p artefacts
    - cp /go/pkg/mod/github.com/muesli/duf\@v${VERSION}/README.md /go/pkg/mod/github.com/muesli/duf\@v${VERSION}/LICENSE artefacts
    - mv /go/bin/duf artefacts/
  only:
    changes:
      - "duf/*"
  artifacts:
    paths:
      - ./artefacts/

rpm.duf:
  extends: .rpm-template
  dependencies:
    - compile.duf
  only:
    changes:
      - "duf/*"
  script:
    - cat ~/.rpmmacros
    - >
      fpm -s dir -t rpm -n ${PACKAGE_NAME} -v ${VERSION}
      --description 'Disk Usage/Free Utility (Linux, BSD & macOS)'
      --rpm-summary 'Disk Usage/Free Utility (Linux, BSD & macOS)'
      --vendor morawskim
      --license MIT
      --url https://github.com/muesli/duf
      ./artefacts/duf=/usr/bin/
      ./artefacts/LICENSE=/usr/share/licenses/${PACKAGE_NAME}/LICENSE
      ./artefacts/README.md=/usr/share/doc/packages/${PACKAGE_NAME}/README.md
  artifacts:
    paths:
      - ${PACKAGE_NAME}-${VERSION}-1.x86_64.rpm
