variables:
  GRON_VERSION: '0.7.1'

compile.gron:
  stage: build
  image: golang:1.19
  script:
    - go install github.com/tomnomnom/gron@v${GRON_VERSION}
    - mkdir -p gron-${GRON_VERSION}
    - mv /go/bin/gron gron-${GRON_VERSION}/gron
    - cp /go/pkg/mod/github.com/tomnomnom/gron\@v${GRON_VERSION}/{README.mkd,LICENSE,ADVANCED.mkd,CHANGELOG.mkd}  gron-${GRON_VERSION}
  only:
    changes:
      - "gron/*"
  artifacts:
    paths:
      - gron-${GRON_VERSION}/

rpm.gron:
    stage: package
    image: alanfranz/fpm-within-docker:centos-7
    variables:
      PACKAGE_NAME: 'gron'
      VERSION: $GRON_VERSION
    dependencies:
      - compile.gron
    only:
      changes:
        - "gron/*"
    before_script:
      - gpg --import $GPG_PRIVATE_KEY_TO_SIGN
      - echo -e "5\ny\n" | gpg --no-tty --command-fd 0 --edit-key "morawskim" trust
    script:
      - |
        cat > ~/.rpmmacros << EOF
        %packager Marcin Morawski <marcin@morawskim.pl>
        %_signature gpg
        %_gpg_name morawskim Signing Key
        %vendor morawskim
        EOF
      - cat ~/.rpmmacros
      - >
        fpm -s dir -t rpm -n ${PACKAGE_NAME} -v ${VERSION}
        --description "gron transforms JSON into discrete assignments to make it easier to grep for what you want and see the absolute 'path' to it. It eases the exploration of APIs that return large blobs of JSON but have terrible documentation."
        --rpm-summary 'Make JSON greppable!'
        --vendor morawskim
        --license 'MIT'
        --url https://github.com/tomnomnom/gron
        ./gron-${GRON_VERSION}/gron=/usr/bin/
        ./gron-${GRON_VERSION}/README.mkd=/usr/share/doc/packages/${PACKAGE_NAME}/README.mkd
        ./gron-${GRON_VERSION}/ADVANCED.mkd=/usr/share/doc/packages/${PACKAGE_NAME}/ADVANCED.mkd
        ./gron-${GRON_VERSION}/CHANGELOG.mkd=/usr/share/doc/packages/${PACKAGE_NAME}/CHANGELOG.mkd
        ./gron-${GRON_VERSION}/LICENSE=/usr/share/licenses/${PACKAGE_NAME}/LICENSE
      - rpm --addsign *.rpm
    artifacts:
      paths:
        - ${PACKAGE_NAME}-*.x86_64.rpm
