stages:
  - build
  - package

variables:
  PACKAGE_NAME: 'htmlq'
  VERSION: '0.4.0'

compile:
  stage: build
  image: rust:1.66
  script:
    - wget -Ohtmlq.tar.gz https://github.com/mgdm/htmlq/archive/v${VERSION}.tar.gz
    - tar xvzf htmlq.tar.gz
    - cd htmlq-${VERSION}
    - cargo build --release
  only:
    changes:
      - "htmlq/*"
  artifacts:
    paths:
      - htmlq-${VERSION}/target/release/htmlq
      - htmlq-${VERSION}/LICENSE.md
      - htmlq-${VERSION}/README.md

rpm:
    stage: package
    image: alanfranz/fpm-within-docker:centos-7
    dependencies:
      - compile
    only:
      changes:
        - "htmlq/*"
    before_script:
      - gpg --import $GPG_PRIVATE_KEY_TO_SIGN
      - echo -e "5\ny\n" | gpg --no-tty --command-fd 0 --edit-key "morawskim" trust
    script:
      - |
        cat > ~/.rpmmacros << EOF
        %packager Marcin Morawski <marcin@morawskim.pl>
        %_signature gpg
        %_gpg_name morawskim Signing Key
        %vendor morawskim
        EOF
      - >
        fpm -s dir -t rpm -n ${PACKAGE_NAME} -v ${VERSION}
        --description 'Like jq, but for HTML. Uses CSS selectors to extract bits of content from HTML files.'
        --rpm-summary 'Like jq, but for HTML.'
        --vendor morawskim
        --license MIT
        --url https://github.com/mgdm/htmlq
        htmlq-${VERSION}/target/release/htmlq=/usr/bin/
        htmlq-${VERSION}/README.md=/usr/share/doc/packages/${PACKAGE_NAME}/
        htmlq-${VERSION}/LICENSE.md=/usr/share/licenses/${PACKAGE_NAME}/
      - rpm --addsign *.rpm
    artifacts:
      paths:
        - ${PACKAGE_NAME}-${VERSION}-1.x86_64.rpm
